MakeupStore.PL/Controllers/BrandController.cs
using AutoMapper;
using MakeupStore.BLL.Interfaces;
using MakeupStore.DAL.Entities;
using MakeupStore.PL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MakeupStore.PL.Controllers
{
    [Authorize(Roles = "Admin")]

    public class BrandController : Controller
    {
        private readonly IBrandRepository _brandRepo;
        private readonly IMapper _mapper;

        public BrandController(IBrandRepository brandRepo, IMapper mapper)
        {
            _brandRepo = brandRepo;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            IEnumerable<ProductBrand> brands;
            IEnumerable<BrandViewModel> brandsVM;

            brands = _brandRepo.GetAll();
            brandsVM = _mapper.Map<IEnumerable<BrandViewModel>>(brands);

            return View(brandsVM);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(BrandViewModel brandVM)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var checkedBrand = _brandRepo.GetByName(brandVM.Name);

                    if (checkedBrand is null)
                    {
                        var brand = _mapper.Map<ProductBrand>(brandVM);
                        _brandRepo.Add(brand);
                        TempData["Message"] = "Brand Created Successfully";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["Message"] = "Brand Already Exist!!";
                        return RedirectToAction("Index");
                    }

                }
                catch (Exception ex)
                {
                    throw new Exception(ex.Message);
                }
            }
            return View(brandVM);
        }

        public IActionResult Details(int? id)
        {
            try
            {
                if (id is null)
                    return RedirectToAction("Error", "Home");

                var brand = _brandRepo.GetById(id);
                var mappedBrand = _mapper.Map<BrandViewModel>(brand);
                if (brand is null)
                    return RedirectToAction("Error", "Home");

                return View(mappedBrand);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public IActionResult Update(int? id)
        {
            if (id is null)
                return RedirectToAction("Error", "Home");

            var brand = _brandRepo.GetById(id);
            var mappedBrand = _mapper.Map<BrandViewModel>(brand);
            if (brand is null)
                return RedirectToAction("Error", "Home");

            return View(mappedBrand);
        }

        [HttpPost]
        public IActionResult Update(int id, BrandViewModel brandVM)
        {
            if (id != brandVM.Id)
                return RedirectToAction("Error", "Home");

            try
            {
                if (ModelState.IsValid)
                {
                    var brand = _mapper.Map<ProductBrand>(brandVM);
                    _brandRepo.Update(brand);
                    return RedirectToAction("Index");
                }
                else
                    return View(brandVM);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public IActionResult Delete(int? id)
        {
            if (id is null)
                return RedirectToAction("Error", "Home");

            var brand = _brandRepo.GetById(id);
            var mappedBrand = _mapper.Map<BrandViewModel>(brand);

            if (mappedBrand is null)
                return RedirectToAction("Error", "Home");

            _brandRepo.Delete(brand);
            return RedirectToAction("Index");
        }
    }
}

MakeupStore.PL/Controllers/CategoryController.cs
using AutoMapper;
using MakeupStore.BLL.Interfaces;
using MakeupStore.DAL.Entities;
using MakeupStore.PL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MakeupStore.PL.Controllers
{
    [Authorize(Roles = "Admin")]

    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _categoryRepo;
        private readonly IMapper _mapper;

        public CategoryController(ICategoryRepository categoryRepo, IMapper mapper)
        {
            _categoryRepo = categoryRepo;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            IEnumerable<ProductCategory> categories;
            IEnumerable<ProductCategoryViewModel> categoriesVM;

            categories = _categoryRepo.GetAll();
            categoriesVM = _mapper.Map<IEnumerable<ProductCategoryViewModel>>(categories);

            return View(categoriesVM);
        }

        public IActionResult AddCategory()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddCategory(ProductCategoryViewModel categoryVM)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var checkedCategory = _categoryRepo.GetByName(categoryVM.Name);

                    if(checkedCategory is null)
                    {
                        var category = _mapper.Map<ProductCategory>(categoryVM);
                        _categoryRepo.Add(category);
                        TempData["Message"] = "Category Created Successfully";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["Message"] = "Category Already Exist!!";
                        return RedirectToAction("Index");
                    }

                }
                catch (Exception ex)
                {
                    throw new Exception(ex.Message);
                }
            }
            return View(categoryVM);
        }

        public IActionResult Details(int? id)
        {
            try
            {
                if (id is null)
                    return RedirectToAction("Error", "Home");

                var category = _categoryRepo.GetById(id);
                var mappedCategory = _mapper.Map<ProductCategoryViewModel>(category);
                if (category is null)
                    return RedirectToAction("Error", "Home");

                return View(mappedCategory);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public IActionResult Update(int? id)
        {
            if (id is null)
                return RedirectToAction("Error", "Home");

            var category = _categoryRepo.GetById(id);

			if (category is null)
				return RedirectToAction("Error", "Home");
			
            var mappedCategory = _mapper.Map<ProductCategoryViewModel>(category);
            

            return View(mappedCategory);
        }

        [HttpPost]
        public IActionResult Update(int id, ProductCategoryViewModel categoryVM)
        {
            if (id != categoryVM.Id)
                return RedirectToAction("Error", "Home");

            try
            {
                if (ModelState.IsValid)
                {
                    var category = _mapper.Map<ProductCategory>(categoryVM);
                    _categoryRepo.Update(category);
                    return RedirectToAction("Index");
                }
                else
                    return View(categoryVM);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public IActionResult Delete(int? id)
        {
            if (id is null)
                return RedirectToAction("Error", "Home");

            var category = _categoryRepo.GetById(id);
            var mappedCategory = _mapper.Map<ProductCategoryViewModel>(category);

            if (mappedCategory is null)
                return RedirectToAction("Error", "Home");

            _categoryRepo.Delete(category);
            return RedirectToAction("Index");
        }
    }
}

MakeupStore.PL/Controllers/OrderController.cs
using AutoMapper;
using MakeupStore.BLL.Interfaces;
using MakeupStore.DAL.Entities;
using MakeupStore.PL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;

namespace MakeupStore.PL.Controllers
{
	[Authorize(Roles = "Admin , Normal User")]

	public class OrderController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IGenericRepository<Order> _orderRepository;
        private readonly IProductRepository _productRepository;
        private readonly IGenericRepository<ProductCategory> _categoryRepo;
        private readonly IGenericRepository<ProductBrand> _brandRepo;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public OrderController(IMapper mapper, UserManager<ApplicationUser> userManager, IGenericRepository<Order> order, IProductRepository productRepository, IGenericRepository<ProductCategory> categoryRepo, IGenericRepository<ProductBrand> brandRepo, SignInManager<ApplicationUser> signInManager)
        {
            _mapper = mapper;
            _orderRepository = order;
            _productRepository = productRepository;
            _categoryRepo = categoryRepo;
            _brandRepo = brandRepo;
            _signInManager = signInManager;
            _userManager = userManager;    
        }

        public IActionResult Index()
        {
            IEnumerable<Order> orders;
            IEnumerable<OrderDetailsViewModel> mappedOrders;
            string username = User.Identity.Name;
            if (_signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
            {
                orders = _orderRepository.GetAll();
            }
            else /*if(_signInManager.IsSignedIn(User) && User.IsInRole("Normal User"))*/
            {
                orders = _orderRepository.GetAll().Where(o => o.Username == username);
            }
            mappedOrders = _mapper.Map<IEnumerable<OrderDetailsViewModel>>(orders);
            
            foreach (var order in mappedOrders)
            {
                order.ProductName = _productRepository.GetById(order.ProductId).Name;
            }

            return View(mappedOrders);
        }

        public IActionResult AddOrder(int? id)
        {
            var product = _productRepository.GetById(id);
            if (product == null)
            {
                return NotFound();
            }
            var orderVM = new OrderViewModel
            {
                ProductId = product.Id,
                Quantity = 1,
                Username = User.Identity.Name,
            };

            return View(orderVM);
        }
        [HttpPost]
        public IActionResult AddOrder(OrderViewModel orderVM)
        {
            var productToOrder = _productRepository.GetById(orderVM.ProductId);

            if (productToOrder == null)
            {
                ModelState.AddModelError("ProductId", "Invalid ProductId");
            }

            if (ModelState.IsValid)
            {
                orderVM.SubTotal = productToOrder.Price * orderVM.Quantity;
                orderVM.TotalPrice = orderVM.SubTotal + orderVM.ShippingPrice;
                orderVM.Username = User.Identity.Name;
                orderVM.DeliveryDate = orderVM.OrderDate.AddDays(3);

                var order = _mapper.Map<Order>(orderVM);

                _orderRepository.Add(order);

                return RedirectToAction(nameof(Index));
            }

            return View(orderVM);
        }

        public IActionResult Delete(int? id)
        {
            if (id is null)
                return NotFound();

            var order = _orderRepository.GetById(id);

            if (order is null)
                return RedirectToAction("Error", "Home");

            _orderRepository.Delete(order);

            //var orderVM = _mapper.Map<OrderViewModel>(order);

            return RedirectToAction("Index");
        }
    }
}

MakeupStore.PL/Controllers/ProductController.cs
using AutoMapper;
using MakeupStore.BLL.Interfaces;
using MakeupStore.DAL.Entities;
using MakeupStore.PL.Helper;
using MakeupStore.PL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MakeupStore.PL.Controllers
{
    [Authorize(Roles = "Admin , Normal User")]
    public class ProductController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IProductRepository _repository;
        private readonly IGenericRepository<ProductCategory> _categoryRepo;
        private readonly IGenericRepository<ProductBrand> _brandRepo;
        public ProductController(IMapper mapper, IProductRepository repository, IGenericRepository<ProductCategory> categoryRepo, IGenericRepository<ProductBrand> brandRepo)
        {
            _mapper = mapper;
            _repository = repository;
            _categoryRepo = categoryRepo;
            _brandRepo = brandRepo;
        }
        public IActionResult Index(string SearchValue = "")
        {
            IEnumerable<Product> products;
            IEnumerable<ProductViewModel> mappedProducts;
            if (string.IsNullOrEmpty(SearchValue))
            {
                products = _repository.GetAll();
                mappedProducts = _mapper.Map<IEnumerable<ProductViewModel>>(products);
            }
            else
            {
                products = _repository.Search(SearchValue);
                mappedProducts = _mapper.Map<IEnumerable<ProductViewModel>>(products);
            }

            return View(mappedProducts);
        }
        [Authorize(Roles = "Admin")]
        public IActionResult AddProduct()
        {
            ViewBag.categories = _categoryRepo.GetAll();
            ViewBag.brands = _brandRepo.GetAll();

            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult AddProduct(ProductViewModel productVM) 
        {
                ViewBag.categories = _categoryRepo.GetAll();
                ViewBag.brands = _brandRepo.GetAll();
            if(ModelState.IsValid)
            {
                try
                {
                    var product = _mapper.Map<Product>(productVM);
                    product.PictureUrl = DocumentSettings.UploadFile(productVM.Image, "Images");

                    _repository.Add(product);
                    return RedirectToAction(nameof(Index));

                }
                catch (Exception ex)
                {

                    throw new Exception(ex.Message);
                }
            }
            return View(productVM);
            
        }
        public IActionResult Details(int? id)
        {
            try
            {
                if (id is null)
                    return NotFound();

                var product = _repository.GetById(id);
                ViewBag.categories = _categoryRepo.GetAll();
                ViewBag.brands = _brandRepo.GetAll();

                if (product is null)
                    return NotFound();

                var productVM = _mapper.Map<ProductViewModel>(product);

                return View(productVM);
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }
        [Authorize(Roles = "Admin")]

        public IActionResult Update(int? id)
        {
            if (id is null)
                return RedirectToAction("Error", "Home");

            var product = _repository.GetById(id);
            ViewBag.categories = _categoryRepo.GetAll();
            ViewBag.brands = _brandRepo.GetAll();

            if (product is null)
                return RedirectToAction("Error", "Home");

            var productVM = _mapper.Map<ProductViewModel>(product);

            return View(productVM);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Update(int id, ProductViewModel productVM)
        {
            if (id != productVM.Id)
                return RedirectToAction("Error", "Home");

            try
            {
                if (ModelState.IsValid)
                {
                    var product = _mapper.Map<Product>(productVM);
                    if (productVM.Image != null)
                        product.PictureUrl = DocumentSettings.UploadFile(productVM.Image, "Images");


                    _repository.Update(product);
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {

                throw new Exception(ex.Message);
            }
            return View(productVM);
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int? id)
        {
            if (id is null)
                return NotFound();

            var product = _repository.GetById(id);

            if (product is null)
                return RedirectToAction("Error", "Home");

            _repository.Delete(product);

            //var productVM = _mapper.Map<ProductViewModel>(product);

            return RedirectToAction("Index");
        }
    }
}

MakeupStore.PL/Views/Shared/_AuthLayout.cshtml
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	<title>Store Register| @ViewData["Title"]</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	@* <script type="application/x-javascript">
		addEventListener("load", function() {
			setTimeout(hideURLbar, 0);
		}, false);
		function hideURLbar(){
			window.scrollTo(0,1);
		}
	</script> *@
	<!-- Custom Theme files -->
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<div class="container" id="container">
			@RenderBody()
		
	</div>

	
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/index.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MakeupStore.PL/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> signInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MakeUp Store</title>
@*     <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
 *@
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MakeupStore.PL.styles.css" asp-append-version="true" />
</head>
<body style="background: rgb(248, 192, 192);">
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MakeUp Store</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @* <li class="nav-item">
                            <a class="nav-link  active" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li> *@
                        @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Brand" asp-action="Index">Brand</a>
                            </li>
                            
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                        </li>
                    </ul>
                    @if (signInManager.IsSignedIn(User))
                    {
                        <ul class="navbar-nav ">
                            <li class="nav-item">
                                <a class="btn btn-danger " asp-controller="Account" asp-action="LogOut">
                                    Log Out <i class="bi bi-box-arrow-left"></i>
                                </a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MakeupStore.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>